#ifndef MQL_AUTO_FORWARDS_INCLUDED_DB680C5D6B4F75C1
#define MQL_AUTO_FORWARDS_INCLUDED_DB680C5D6B4F75C1
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/CarixStudio/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/mns-engine/Experts/MNS_TestHarness/MNS_TestHarness.mq5


#endif
