#ifndef MQL_AUTO_FORWARDS_INCLUDED_3868B29E500AE74E
#define MQL_AUTO_FORWARDS_INCLUDED_3868B29E500AE74E
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in c:/Users/CarixStudio/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075/MQL5/mns-engine/src/Experts/MNS_TestHarness/MNS_TestHarness.mq5


#endif
